[tool.poetry]
name = "playlist"
version = "0.1.0"
description = ""
authors = ["enpuyou <youe2@allegheny.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
spotipy = "^2.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
